FROM jupyter/datascience-notebook:python-3.8.6

RUN pip install git+https://github.com/tdoehmen/duckdq.git
RUN pip install great_expectations pymysql duckdb_engine vaex datatable dask

COPY work_B/eval_b.ipynb /home/jovyan/eval_b_script.ipynb
ADD data/hotel_search_logs_3M_small.tar.gz /home/jovyan/data/
RUN jupyter nbconvert --to script /home/jovyan/eval_b_script.ipynb
RUN rm /home/jovyan/eval_b_script.ipynb